apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-file
  namespace: hubs
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: secrettask
      mountPath: "/secrets"
      readOnly: true
  volumes:
  - name: secrettask
    secret:
      secretName: mysecret
      optional: false
